### ISSUE TITLE
Can't connect to the elasticsearch server

### ISSUE THREAD

**Issue by garyfeng** [garyfeng/board#2]
The docker compose file has the following, where it just pulled a standard elasticsearch image. Don't know which version, but if it's 2.0, presumably is it not forwarding the IP to the VM. 

```
data:
  image: busybox
  volumes:
    - /usr/share/elasticsearch/data
    - /var/lib/postgresql/data
    - /usr/share/nginx/html/media
  command: tail -f /dev/null
  restart: always

elasticsearch:
  image: elasticsearch
  volumes_from:
    - data
  restart: always

postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: something
  volumes_from:
    - data
  restart: always

restyaboard:
  build: .
  links:
    - elasticsearch:elasticsearch
    - postgres:postgres
  ports:
    - 1234:80
  volumes_from:
    - data
  restart: always

```

See http://dockerfile.github.io/#/elasticsearch for the elasticsearch official docker file. Note that this is using the 1.5 version.

since I am using Docker Tools, I am also using docker-machine. See info on

```
docker-machine inspect default
```

ElasticSearch is not exposing its ports. On OSX we need 2 layers of port forwarding, from the VM ==> boot2docker ==> localhost. See http://blog.tutum.co/2015/05/19/guide-to-docker-on-os-x/ for potential solutions.

So I should SSH to the VM, where I will find the boot2docker command, and presumably the images/containers. Then I can add the network command to the elasticsearch.yml . See https://hub.docker.com/r/library/elasticsearch/
